image: openjdk:9-jdk-slim

pipelines:
  default:
    - step:
        caches:
          - gradle
        image: openjdk:9-jdk-slim
        script:
          - apt install -y git
          - git submodule update --init
          - ./gradlew test
