pipelines:
  default:
    - step:
        name: fetch code
        script:
          - git submodule update --init
    - step:
        name: build
        image: openjdk:11-jdk-slim
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew compileJava
    - step:
        name: test
        image: openjdk:11-jdk-slim
        caches:
          - gradle
          - gradlewrapper
        script:
          - apt-get update
          - apt-get install -y git
          - git submodule update --init
          - ./gradlew test

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
