image: openjdk:9-jdk-slim

pipelines:
  default:
    - step:
        caches:
          - gradle
        image: alpine/git
        script:
          - git submodule update --init
    - step:
        caches:
          - gradle
        image: openjdk:9-jdk-slim
        script:
          - ./gradlew test
