image: openjdk:11-jdk-slim

pipelines:
  default:
    - step:
        caches:
          - docker
          - gradle
          - gradlewrapper
        script:
          - apt-get update
          - apt-get install -y git
          - git submodule update --init
          - ./gradlew test
          - ./gradlew shadowJar

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
