name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build
      run: ./gradlew clean jlink
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker Build
      run: docker build -t ${{ secrets.DOCKER_HUB_REPO }}/holocore:$GITHUB_REF .
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_HUB_REPO }}/holocore:$GITHUB_REF
