name: Deploy to QA

on:
  push:
    branches:
      - quality_assurance

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build
      run: ./gradlew --no-daemon clean jlink
    - name: Docker Login
      run: docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"
    - name: Docker Build
      run: docker build -t "${{secrets.DOCKER_IMAGE }}:quality_assurance" .
    - name: Docker Push
      run: docker push "${{secrets.DOCKER_IMAGE }}:quality_assurance"
