name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Docker Login
      run: docker login -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ./gradlew clean jlink
