name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build
      run: ./gradlew clean jlink
    - name: Docker Login
      run: docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"
    - name: Docker Build
      run: docker build -t "docker.pkg.github.com/$GITHUB_REPOSITORY/holocore:$GITHUB_REF" .
    - name: Docker Push
      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/holocore:$GITHUB_REF"
